[mypy]
warn_unused_configs = True
warn_unused_ignores = True
warn_unreachable = True
warn_return_any = True

[mypy-aiogram,aiogram.*]
ignore_missing_imports = True

[mypy-keyboards,keyboards.*]
ignore_missing_imports = True

[mypy-work_with_db,work_with_db.*]
ignore_missing_imports = True

[mypy-PIL,PIL.*]
ignore_missing_imports = True

[mypy-apscheduler,apscheduler.*]
ignore_missing_imports = True

[mypy-pyppeteer]
ignore_missing_imports = True

[mypy-bs4]
ignore_missing_imports = True
